language: python
os: linux
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libopenmpi-dev openmpi-bin
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install 'NEURON>=7.8.0,<7.8.1'
  - pip3 install -e . --no-use-pep517
  - pip3 install coverage
script:
  - coverage run --parallel-mode -m unittest discover -v -s ./tests
  - mpiexec -n 4 coverage run --parallel-mode -m unittest discover -v -s ./tests
after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)
