language: python
os: linux
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
      before_install:
        - sudo apt-get install -y openmpi-bin
        - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
        - sudo dpkg -i nrn-7.7.x86_64-linux.deb
        - export PYTHONPATH=$PYTHONPATH:/usr/local/nrn/lib/python
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -e . --no-use-pep517
  - pip3 install coverage
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
